project:
  type: website
  output-dir: _output

website:
  title: 'Quarto Review Example'
  navbar:
    left:
      - text: 'Home'
        file: document.qmd
      - text: 'Debug'
        file: debug-example.qmd
      - text: 'Translation'
        file: doc-translation.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

review:
  enabled: true
  enableTranslation: true
  debug:
    enabled: true
    level: debug
  git:
    provider: github
    owner: mvwestendorp
    repo: quarto-review-extension-github-demo-new
    base-branch: main # optional; defaults to `main`
    auth:
      mode: pat
  user:
    auth:
      mode: 'oauth2-proxy'
      userHeader: 'x-auth-request-user'
      emailHeader: 'x-auth-request-email'
      usernameHeader: 'x-auth-request-preferred-username'
      defaultRole: 'editor'
      debug: true

filters:
  - review
